# Generated by Django 5.0.6 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminuser',
            name='admin_users_deactivated_implies_inactive',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(condition=models.Q(('deactivated_at__isnull', True)), fields=['active'], name='admin_users_active_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['role'], name='admin_users_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminuser',
            constraint=models.CheckConstraint(check=models.Q(('deactivated_at__isnull', True), ('active', False), _connector='OR'), name='admin_users_deactivated_implies_inactive'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
