# Generated by Django 5.0.6 on 2026-07-21 10:39

import apps.users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_adminuser_admin_users_deactivated_implies_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=apps.users.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
