# Generated by Django 5.0.6 on 2026-07-12 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chn_code', models.CharField(max_length=20, unique=True)),
                ('patient_ref', models.CharField(max_length=64)),
                ('image_path', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING_AI', 'Pendiente de IA'), ('PROCESSING', 'En procesamiento'), ('READY', 'Listo'), ('VALIDATED', 'Validado'), ('REJECTED', 'Rechazado')], default='PENDING_AI', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples_as_analyst', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples_as_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(check=models.Q(('is_active', False), ('deleted_at__isnull', True), _negated=True), name='samples_deactivated_implies_deleted_at'),
        ),
    ]
