# Generated by Django 5.0.6 on 2026-07-12 16:38

import apps.samples.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chn_code', models.CharField(max_length=20, unique=True)),
                ('full_name', apps.samples.fields.EncryptedTextField()),
                ('birth_date', apps.samples.fields.EncryptedTextField(blank=True, default='')),
                ('document_id', apps.samples.fields.EncryptedTextField(blank=True, default='')),
                ('phone', apps.samples.fields.EncryptedTextField(blank=True, default='')),
                ('indication', apps.samples.fields.EncryptedTextField(blank=True, default='')),
                ('family_history', apps.samples.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinic_patient_vault',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='analysis_requests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='culture_method',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='department',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='reception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='requesting_doctor',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('sangre', 'Sangre periférica'), ('medula', 'Médula ósea'), ('amniotico', 'Líquido amniótico'), ('vellosidades', 'Vellosidades coriales')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_ref',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_AI', 'Pendiente de IA'), ('PROCESSING', 'En procesamiento'), ('READY', 'Listo'), ('VALIDATED', 'Validado'), ('REJECTED', 'Rechazado')], default='PENDING_AI', max_length=20),
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('camera', 'Cámara'), ('upload', 'Archivo subido')], max_length=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samples.sample')),
            ],
            options={
                'db_table': 'clinic_sample_images',
                'ordering': ['order', 'captured_at'],
            },
        ),
    ]
