# Generated by Django 5.0.6 on 2026-07-17 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_patientvault_sample_analysis_requests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'clinic_rbac_grupo',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'clinic_rbac_objeto',
            },
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'clinic_rbac_tipo_objeto',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='samples.objeto')),
            ],
            options={
                'db_table': 'clinic_rbac_opcion',
            },
        ),
        migrations.CreateModel(
            name='PrivilegioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios', to='samples.grupo')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios_grupo', to='samples.opcion')),
            ],
            options={
                'db_table': 'clinic_rbac_privilegio_grupo',
            },
        ),
        migrations.CreateModel(
            name='PrivilegioIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=None, null=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios_individuales', to='samples.opcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_rbac_privilegio_individual',
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='samples.tipoobjeto'),
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='samples.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_clinicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_rbac_usuario_grupo',
            },
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('objeto', 'nombre'), name='uniq_objeto_opcion_nombre'),
        ),
        migrations.AddConstraint(
            model_name='privilegiogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'opcion'), name='uniq_grupo_opcion'),
        ),
        migrations.AddConstraint(
            model_name='privilegioindividual',
            constraint=models.UniqueConstraint(fields=('usuario', 'opcion'), name='uniq_usuario_opcion_individual'),
        ),
        migrations.AddConstraint(
            model_name='usuariogrupo',
            constraint=models.UniqueConstraint(fields=('usuario', 'grupo'), name='uniq_usuario_grupo'),
        ),
    ]
