# Generated by Django 5.0.6 on 2026-07-24 05:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_sample_status_karyotype_chromosome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('XAI_VIEWED', 'XAI consultado'), ('ACCEPT_CHROMOSOME', 'Cromosoma aceptado'), ('RECLASSIFY', 'Reclasificado'), ('CORRECT_CLASS', 'Clase corregida'), ('MARK_ANOMALY', 'Anomalía marcada'), ('SPLIT', 'Separado'), ('JOIN', 'Unido'), ('RESOLVE_CROSS', 'Cruce resuelto'), ('ANALYST_VALIDATED', 'Validado por analista'), ('AUDIT_DECISION', 'Decisión de auditoría'), ('ISCN_OVERRIDE', 'Override ISCN'), ('SIGN_REPORT', 'Reporte firmado')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('current_hash', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('chromosome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='samples.chromosome')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='samples.sample')),
            ],
            options={
                'db_table': 'clinic_audit_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sample', 'created_at'], name='clinic_audi_sample__685bb5_idx')],
            },
        ),
    ]
