# Generated by Django 5.0.6 on 2026-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_chromosome_is_anomaly_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
