# Generated by Django 5.0.6 on 2026-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_chromosome_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='mode',
            field=models.CharField(choices=[('auto', 'Automático (con IA)'), ('degradado', 'Modo degradado (manual, sin IA)')], default='auto', max_length=10),
        ),
    ]
