# Generated by Django 5.0.6 on 2026-07-24 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auditevent_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_AI', 'Pendiente de IA'), ('PROCESSING', 'En procesamiento'), ('READY', 'Listo'), ('BLOCKED_BY_CONFIDENCE', 'Bloqueado por confianza'), ('ANALYST_VALIDATED', 'Validado por analista'), ('SIGNED', 'Firmado por supervisor'), ('REPORTED', 'Reportado (ISCN)'), ('VALIDATED', 'Validado'), ('REJECTED', 'Rechazado')], default='PENDING_AI', max_length=24),
        ),
        migrations.CreateModel(
            name='AuditReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reviews', to='samples.chromosome')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_reviews', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reviews', to='samples.sample')),
            ],
            options={
                'db_table': 'clinic_audit_reviews',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='auditreview',
            constraint=models.UniqueConstraint(fields=('sample', 'chromosome'), name='uniq_audit_review_per_chromosome'),
        ),
    ]
