# Generated by Django 5.0.6 on 2026-07-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_seed_case_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='narrative_draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sample',
            name='narrative_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='narrative_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('XAI_VIEWED', 'XAI consultado'), ('ACCEPT_CHROMOSOME', 'Cromosoma aceptado'), ('RECLASSIFY', 'Reclasificado'), ('CORRECT_CLASS', 'Clase corregida'), ('MARK_ANOMALY', 'Anomalía marcada'), ('SPLIT', 'Separado'), ('JOIN', 'Unido'), ('RESOLVE_CROSS', 'Cruce resuelto'), ('ANALYST_VALIDATED', 'Validado por analista'), ('AUDIT_DECISION', 'Decisión de auditoría'), ('ISCN_OVERRIDE', 'Override ISCN'), ('SIGN_REPORT', 'Reporte firmado'), ('NARRATIVE_GENERATED', 'Narrativa generada (LLM)')], max_length=20),
        ),
    ]
