# Generated by Django 5.0.6 on 2026-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_sample_narrative_draft_sample_narrative_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='iscn_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='iscn_is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='iscn_nomenclature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
