# Generated by Django 5.0.6 on 2026-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_seed_case_override_iscn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('XAI_VIEWED', 'XAI consultado'), ('ACCEPT_CHROMOSOME', 'Cromosoma aceptado'), ('RECLASSIFY', 'Reclasificado'), ('CORRECT_CLASS', 'Clase corregida'), ('MARK_ANOMALY', 'Anomalía marcada'), ('SPLIT', 'Separado'), ('JOIN', 'Unido'), ('RESOLVE_CROSS', 'Cruce resuelto'), ('RECROP', 'Recorte corregido'), ('ANALYST_VALIDATED', 'Validado por analista'), ('AUDIT_DECISION', 'Decisión de auditoría'), ('ISCN_OVERRIDE', 'Override ISCN'), ('SIGN_REPORT', 'Reporte firmado'), ('NARRATIVE_GENERATED', 'Narrativa generada (LLM)')], max_length=20),
        ),
    ]
