# Generated by Django 5.0.6 on 2026-07-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=128)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_password_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='admin_passw_user_id_96d124_idx')],
            },
        ),
    ]
