# Generated by Django 5.0.6 on 2026-07-22 03:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0002_passwordhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('unet_version', models.CharField(default='u-net-v2.1', max_length=40)),
                ('unet_enabled', models.BooleanField(default=True)),
                ('classifier_version', models.CharField(default='efficientnet-b3-v1.4', max_length=40)),
                ('classifier_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.850'), max_digits=4)),
                ('detection_sensitivity', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4)),
                ('analysis_mode', models.CharField(choices=[('fast', 'Rápido (prioriza velocidad)'), ('balanced', 'Balanceado'), ('accurate', 'Precisión máxima (más lento)')], default='balanced', max_length=16)),
                ('log_level', models.CharField(choices=[('WARNING', 'Mínimo'), ('INFO', 'Normal'), ('DEBUG', 'Detallado')], default='INFO', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_model_config',
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('precision_overall', models.DecimalField(decimal_places=4, max_digits=5)),
                ('precision_per_class', models.JSONField(blank=True, default=dict)),
                ('recall_overall', models.DecimalField(decimal_places=4, max_digits=5)),
                ('f1_overall', models.DecimalField(decimal_places=4, max_digits=5)),
                ('latency_p50_ms', models.IntegerField()),
                ('latency_p95_ms', models.IntegerField()),
                ('latency_p99_ms', models.IntegerField()),
                ('samples_evaluated', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_model_metrics',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['-measured_at'], name='admin_model_measure_f9f7b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(check=models.Q(('confidence_threshold__gte', 0), ('confidence_threshold__lte', 1)), name='admin_model_config_confidence_0_1'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(check=models.Q(('detection_sensitivity__gte', 0), ('detection_sensitivity__lte', 1)), name='admin_model_config_sensitivity_0_1'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.CheckConstraint(check=models.Q(('analysis_mode__in', ['fast', 'balanced', 'accurate'])), name='admin_model_config_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='admin_model_config_single_active'),
        ),
    ]
