# Generated by Django 5.0.6 on 2026-07-22 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0003_modelconfig_modelmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_review_pending', models.BooleanField(default=True)),
                ('email_supervisor_validation', models.BooleanField(default=True)),
                ('email_system_errors', models.BooleanField(default=True)),
                ('email_training_completed', models.BooleanField(default=False)),
                ('inapp_review_pending', models.BooleanField(default=True)),
                ('inapp_supervisor_validation', models.BooleanField(default=True)),
                ('inapp_system_errors', models.BooleanField(default=True)),
                ('inapp_training_completed', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='20:00')),
                ('quiet_hours_end', models.TimeField(default='07:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
                'db_table': 'admin_notification_prefs',
            },
        ),
    ]
