# Generated by Django 5.0.6 on 2026-07-22 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0004_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearancePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático (sistema)')], default='light', max_length=8)),
                ('density', models.CharField(choices=[('compact', 'Compacto'), ('comfortable', 'Cómodo'), ('spacious', 'Espacioso')], default='comfortable', max_length=12)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5)),
                ('font_size', models.CharField(choices=[('sm', 'Pequeño'), ('md', 'Mediano'), ('lg', 'Grande')], default='md', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de apariencia',
                'verbose_name_plural': 'Preferencias de apariencia',
                'db_table': 'admin_appearance_prefs',
            },
        ),
        migrations.AddConstraint(
            model_name='appearancepreference',
            constraint=models.CheckConstraint(check=models.Q(('theme__in', ['light', 'dark', 'auto'])), name='admin_appearance_theme_valid'),
        ),
        migrations.AddConstraint(
            model_name='appearancepreference',
            constraint=models.CheckConstraint(check=models.Q(('density__in', ['compact', 'comfortable', 'spacious'])), name='admin_appearance_density_valid'),
        ),
        migrations.AddConstraint(
            model_name='appearancepreference',
            constraint=models.CheckConstraint(check=models.Q(('language__in', ['es', 'en', 'pt'])), name='admin_appearance_language_valid'),
        ),
        migrations.AddConstraint(
            model_name='appearancepreference',
            constraint=models.CheckConstraint(check=models.Q(('font_size__in', ['sm', 'md', 'lg'])), name='admin_appearance_font_size_valid'),
        ),
    ]
